const dressImages = {
  ANA: require('../assets/img/Shirts/dressANA.png'),
  ARI: require('../assets/img/Shirts/dressARI.png'),
  BOS: require('../assets/img/Shirts/dressBOS.png'),
  BUF: require('../assets/img/Shirts/dressBUF.png'),
  CAR: require('../assets/img/Shirts/dressCAR.png'),
  CGY: require('../assets/img/Shirts/dressCGY.png'),
  CHI: require('../assets/img/Shirts/dressCHI.png'),
  CBJ: require('../assets/img/Shirts/dressCBJ.png'),
  COL: require('../assets/img/Shirts/dressCOL.png'),
  DAL: require('../assets/img/Shirts/dressDAL.png'),
  DET: require('../assets/img/Shirts/dressDET.png'),
  EDM: require('../assets/img/Shirts/dressEDM.png'),
  FLA: require('../assets/img/Shirts/dressFLA.png'),
  LAK: require('../assets/img/Shirts/dressLAK.png'),
  MIN: require('../assets/img/Shirts/dressMIN.png'),
  MTL: require('../assets/img/Shirts/dressMTL.png'),
  NSH: require('../assets/img/Shirts/dressNSH.png'),
  NJD: require('../assets/img/Shirts/dressNJD.png'),
  NYI: require('../assets/img/Shirts/dressNYI.png'),
  NYR: require('../assets/img/Shirts/dressNYR.png'),
  OTT: require('../assets/img/Shirts/dressOTT.png'),
  PHI: require('../assets/img/Shirts/dressPHI.png'),
  PIT: require('../assets/img/Shirts/dressPIT.png'),
  SJS: require('../assets/img/Shirts/dressSJS.png'),
  STL: require('../assets/img/Shirts/dressSTL.png'),
  TBL: require('../assets/img/Shirts/dressTBL.png'),
  TOR: require('../assets/img/Shirts/dressTOR.png'),
  VAN: require('../assets/img/Shirts/dressVAN.png'),
  VGK: require('../assets/img/Shirts/dressVGK.png'),
  WPG: require('../assets/img/Shirts/dressWPG.png'),
  WSH: require('../assets/img/Shirts/dressWSH.png'),
  SEA: require('../assets/img/Shirts/dressSEA.png'),
};
export default dressImages;
