const images = {
  ANA: require('../assets/img/Circle/circleANA.png'),
  ARI: require('../assets/img/Circle/circleARI.png'),
  BOS: require('../assets/img/Circle/circleBOS.png'),
  BUF: require('../assets/img/Circle/circleBUF.png'),
  CAR: require('../assets/img/Circle/circleCAR.png'),
  CGY: require('../assets/img/Circle/circleCGY.png'),
  CHI: require('../assets/img/Circle/circleCHI.png'),
  CBJ: require('../assets/img/Circle/circleCBJ.png'),
  COL: require('../assets/img/Circle/circleCOL.png'),
  DAL: require('../assets/img/Circle/circleDAL.png'),
  DET: require('../assets/img/Circle/circleDET.png'),
  EDM: require('../assets/img/Circle/circleEDM.png'),
  FLA: require('../assets/img/Circle/circleFLA.png'),
  LAK: require('../assets/img/Circle/circleLAK.png'),
  MIN: require('../assets/img/Circle/circleMIN.png'),
  MTL: require('../assets/img/Circle/circleMTL.png'),
  NSH: require('../assets/img/Circle/circleNSH.png'),
  NJD: require('../assets/img/Circle/circleNJD.png'),
  NYI: require('../assets/img/Circle/circleNYI.png'),
  NYR: require('../assets/img/Circle/circleNYR.png'),
  OTT: require('../assets/img/Circle/circleOTT.png'),
  PHI: require('../assets/img/Circle/circlePHI.png'),
  PIT: require('../assets/img/Circle/circlePIT.png'),
  SJS: require('../assets/img/Circle/circleSJS.png'),
  STL: require('../assets/img/Circle/circleSTL.png'),
  TBL: require('../assets/img/Circle/circleTBL.png'),
  TOR: require('../assets/img/Circle/circleTOR.png'),
  VAN: require('../assets/img/Circle/circleVAN.png'),
  VGK: require('../assets/img/Circle/circleVGK.png'),
  WPG: require('../assets/img/Circle/circleWPG.png'),
  WSH: require('../assets/img/Circle/circleWSH.png'),
  SEA: require('../assets/img/Circle/circleSEA.png'),
};
export default images;
